### ISSUE TITLE
app.UseRouting() causes crash when user types url in browser

### ISSUE THREAD

**Issue by sam-wheat** [BitzArt/Blazor.Auth#10]
Run the attached app
Click Auth Required Page on the nav menu
RequiresAuth page is displayed correctly.
Click Home on the nav menu
Click on the browser url box and type /RequiresAuth and press enter
An exception is thrown:
> InvalidOperationException: Endpoint /RequiresAuth (/RequiresAuth) contains authorization metadata, but a middleware was not found that supports authorization.  Configure your application startup by adding app.UseAuthorization() in the application startup code. If there are calls to app.UseRouting() and app.UseEndpoints(...), the call to app.UseAuthorization() must go between them.

Modify Program.cs in the server project - comment out `app.UseRouting()`.
Run the steps above and no exception is thrown.
BTW, it appears that the position of `app.UseRouting()` relative to `app.MapAuthEndpoints()` is not relevant.
[Bitzart.Blazor.Auth.Example.zip](https://github.com/BitzArt/Blazor.Auth/files/15351588/Bitzart.Blazor.Auth.Example.zip)

**Comment by YuriyDurov** [comment]
@sam-wheat 

The issue is described [here](https://github.com/dotnet/aspnetcore/issues/52530) and currently seems to appear when using custom AuthenticationStateProviders like the one from this package. You could try adding this code to your server project:

```csharp
builder.Services.Configure<RouteOptions>(options =>
{
    options.SuppressCheckForUnhandledSecurityMetadata = true;
});
```

**Comment by sam-wheat** [comment]
Hi @YuriyDurov , I added this to the server project in my production app and it fixed the problem.  

I hope this makes it your documentation as it took me a while to isolate what the problem was.

Adding the option you show will cause anything not in an `AuthorizieView` to be displayed on the page the user navigates too.  This may or may not be the desired behavior.  In my case I wanted to navigate the user to the login page if they are not authorized.  I was able to modify `routes.razor` in the client project as shown:

	<Router AppAssembly="typeof(Program).Assembly">
		<Found Context="routeData">
			<AuthorizeRouteView RouteData="routeData" DefaultLayout="typeof(Shared.MainLayout)">
				<NotAuthorized>
					<RedirectToLogin />
				</NotAuthorized>
			</AuthorizeRouteView>
			<FocusOnNavigate RouteData="routeData" Selector="h1" />
		</Found>
	</Router>


Also add this component named `RedirectToLogin.razor`


	@inject NavigationManager NavigationManager

	@code {
		protected override void OnInitialized()
		{
			NavigationManager.NavigateTo($"/?returnUrl={Uri.EscapeDataString(NavigationManager.Uri)}", forceLoad: true);
		}
	}


Now when the user types a page in the browser address box and they have not logged in they will be redirected to the login page.
