### ISSUE TITLE
AllowAnonymous does not work

### ISSUE THREAD

**Issue by franky1017** [BitzArt/Blazor.Auth#16]
I created a simple page in my BlazorApp (InteractiveAuto)  and set it to be public. Here is the simple code:

```
`@page "/test"
@attribute [AllowAnonymous]

<h3>Test</h3>

@code {

}
```
The page loads briefly with the word "Test" on the page but then redirected to the login page. I couldn't figure out why. Can you provide some guidance as how I can create public pages that do not require authentication/authorization?

By the way, I created these pages in both the server app and the client app, same.

Thanks!

**Comment by YuriyDurov** [comment]
Hello @franky1017 

For guidance on Blazor authentication capabilities, refer to Blazor [documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0) on the topic.

Normally in a Blazor application pages are available to unauthenticated users by default, unless you mark the page with an `[Authorize]` attribute.

**Comment by franky1017** [comment]
I have specified [AllowAnonymous] on the page. The page briefly shows the
content and within a second, it redirects to login.

I am not doing anything on the page, just static content. Anything you can
think of that will redirect the page to login after a brief second? I've
never had this behavior with other Blazor app before and this is the first
time I am using your component. Any advice is appreciated.

Frank

**Comment by YuriyDurov** [comment]
@franky1017

It seems like something may be interfering with your Blazor request pipeline. Try creating a new Blazor project and then following the [steps](https://bitzart.github.io/Blazor.Auth/02.getting-started.html) from Blazor.Auth documentation and see if it works for you.

Also, I can take a look at your solution if you attach it to this issue.

**Comment by franky1017** [comment]
Never mind, it's my bad. I had a redirect in the MainLayout. Even though
the page uses a public layout, the main one is referenced in Routes. That's
why it's executed every time.

Frank
