### ISSUE TITLE
Extend the login process beyond the basic method

### ISSUE THREAD

**Issue by franky1017** [BitzArt/Blazor.Auth#18]
Right now, your component provides a single authentication method GetSignInResultAsync() by passing a login request object.

However, there are many cases where additional authentication methods are needed. For example, I could let user in from another application by using a mutually agreed token value. Or I could allow an admin to impersonate into another user's account by simply having the user's id (of course, I will manage permission myself).

These additional authentication process are not supported and I have to expand the default username/password login request model to include these fields and handle all these different scenarios in the single login method.

Maybe I am missing something, but please advice.

Thanks,

Frank

**Comment by YuriyDurov** [comment]
@franky1017 

There are no "default request models", those provided in the sample are just example classes for the purpose of demonstrating the package's functionality. You are free to define any models you need.

The package's responsibility is to manage the user's JWT via browser cookies, and to make those work with Blazor's built-in authorization capabilities.

You are free to implement any flow that includes working with JWT in your application logic. But your application's logic is not the responsibility of Blazor.Auth.

**Comment by franky1017** [comment]
@YuriyDurov 

I understand there is no default request model, but there is only one single GetSignInResultAsync() function for the entire app's authentication method, no? How can I use different request models for different authentication workflows/processes?

**Comment by YuriyDurov** [comment]
@franky1017 

You can see the Sign-In method as a method where some request data goes in, and the user gets some JWT in their cookies as a result.

The contract models are not limited here in any way, except for the fact that these models need to be serializable and deserializable for them to be able to get passed between the server and the client parts of the app.

For example, you could create your different processes' models as subclasses from some base class, and use that base class in the generic definition. Then you can check which subclass the model is in the logic of processing the Sign-In request. You could also have some enum indicating which process is currently taking place. You can do a number of different things, I am not able to advise you more on how your end application should look exactly, as this is outside of the scope of this package.

Just make sure to follow these guidelines:

1. Use the Sign-In method as `something goes in, the user gets a JWT pair (that you provide) as a result`;
2. The sign-in request payloads need to be serializable and deserializable;
3. Deserialization process is using the model type that you provide in the server-side `IAuthenticationService`'s generic definition (something like `JsonSerializer.Deserialize<MySignInModel>(json)`).

For additional guidance, refer to the [sequence diagrams](https://bitzart.github.io/Blazor.Auth/04.use-cases.html) provided in the docs.

You provide the data, Blazor.Auth simply passes it back and forth. You can use the Sign-In method to handle all these situations that you described here.

If all this is still not enough, you can provide your custom `IAuthenticationService` implementations when registering Blazor.Auth in your app (for both [client](https://github.com/BitzArt/Blazor.Auth/blob/main/src/BitzArt.Blazor.Auth.Client/Extensions/AddBlazorAuthExtension.cs) and [server](https://github.com/BitzArt/Blazor.Auth/blob/main/src/BitzArt.Blazor.Auth.Server/Extensions/AddBlazorAuthExtension.cs)).

Hope this helps.

**Comment by franky1017** [comment]
> Then you can check which subclass the model is in the logic of processing the Sign-In request.

This is exactly what I am doing. In the sign-in request, I am doing checks to see what type of request model it is and perform different sign in method accordingly.

I was just wishing there could be different sign in methods instead of the single entry point. But it works just fine this way.

Thanks a lot for your time and explanation.

Frank
