### ISSUE TITLE
RefreshJwtPairAsync() is never called until page refresh

### ISSUE THREAD

**Issue by franky1017** [BitzArt/Blazor.Auth#21]
I downloaded your sample app and set the access token to expire in 10 seconds and refresh token 2 minutes. I then logged into the app, clicking around to make sure 10 seconds have passed. But the RefreshJwtPairAsync() was never called and the auth page continues to work without forcing re-login.

As soon as I click reload on my browser, RefreshJwtPairAsync() was called immediately and a new access token was issued as expected.

Can you help me understand this behavior? Why is a physical reload is needed to trigger token refresh? Or did I misunderstand the component usage? Thanks!

**Comment by YuriyDurov** [comment]
Hello @franky1017 

Refresh can only occur when the `AuthenticationStateProvider` is called. Blazor gets the authentication state once per scope and does not update it unless the scope changes. In InteractiveServer, there is one scope per page. In InteractiveWebassembly, the  scope is a bit more complicated. This is how Blazor behaves.

If you plan on making http requests to some WebAPI where you need the access token, we recommend resolving the `AuthenticationStateProvider` from your DI container and calling it's `GetAuthenticationStateAsync` method. The access token will be refreshed while resolving the authentication state. And you can then use the resulting token in your requests.

**Comment by franky1017** [comment]
Got it, thanks for the clarification!

Frank

**Comment by franky1017** [comment]
@YuriyDurov 

I tried to implement AuthenticationStateProvider in DI and it doesn't seem to be working. This is what I've done:

I've create a class like this:
`    public class CustomAuthStateProvider : AuthenticationStateProvider
    {
        public async override Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, "John Doe"),
                new Claim(ClaimTypes.Role, "Administrator")
            };
            var anonymous = new ClaimsIdentity();
            return await Task.FromResult(new AuthenticationState(new ClaimsPrincipal(anonymous)));
        }
    }`

Don't worry about what's inside the function, I just put some dummy codes in there. And this is the updated Program.cs:

`builder.Services.AddAuthorizationCore();
builder.Services.AddCascadingAuthenticationState();

builder.Services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
builder.AddBlazorAuth();`

Once this is done, I put a debug break on GetAuthenticationStateAsync() as well as RefreshJwtPairAsync(), none of them were called on normal navigations. On page reload, RefreshJwtPairAsync() was called, but GetAuthenticationStateAsync() was never called.

I must have missed some other settings? Can you point me to the right configurations? Thanks a lot!

**Comment by franky1017** [comment]
@YuriyDurov I found the codes where your package already implements AuthenticationStateProvider(), thanks for pointing it out.

But I am not sure what you mean by "resolve the AuthenticationStateProvider from your DI container and then use it to retrieve the user's authentication state"? Can you give me a quick sample code? 

All I am trying to achieve is to force token refresh when page navigation occurs or when api needs to be called. Thanks again.

**Comment by franky1017** [comment]
I think I got it! I implemented a class like this:

   ```
 public class AuthTest
    {
        private readonly AuthenticationStateProvider _authenticationStateProvider;

        public AuthTest(AuthenticationStateProvider authenticationStateProvider)
        {
            _authenticationStateProvider = authenticationStateProvider;
        }

        public async Task<IIdentity> GetIdentity()
        {
            var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
            var user = authState.User;
            return user.Identity;
        }
    }
```

I then add this class to DI:

builder.Services.AddScoped<AuthTest>();

On the testing page, I added this:

@inject AuthTest authTest;
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        var identity = await authTest.GetIdentity();
    }

This seems to be working, but I can't consistently get the refresh token function called. Really strange. If I keep clicking between Home and my test page, it's never called. If I sit idle for a while, then start clicking again, it would call refresh token.

Anyway, can you let me know if I am on the right track here? Thanks!

**Comment by franky1017** [comment]
I keep answering my own questions :-) This is it --

```
        public async Task<string> GetToken()
        {
            var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
            var token = authState.User.Claims.FirstOrDefault(x => x.Type == "AccessToken");
            return token.Value;
        }
```

If I am on the right track, I really wish you would include these codes in your sample solution. After all, for those who uses the Blazor App .net 8 will typically always call API from client-side.
