### ISSUE TITLE
The server endpoints how to secure

### ISSUE THREAD

**Issue by T3mmyKay** [BitzArt/Blazor.Auth#22]
I am trying to use your package to secure my server endpoints but they are still open.

On the server project program.cs

 app.MapAuthEndpoints();

 app.MapGet("/api/requires_auth", () => new { message = "Hello, World!" }).RequireAuthorization();
 
 this route when put in the browser is still accessible even when not logged in.
 
 Is there something extra I am supposed to do.

**Comment by YuriyDurov** [comment]
Hello @T3mmyKay, you can use a separate process for securing your WebAPI endpoints. **Blazor.Auth** focuses on implementing Blazor's `AuthenticationStateProvider` and does not really cover anything regarding securing WebAPIs.

After you have secured your WebAPI, you can then make authenticated requests to it from the Blazor app by injecting an `AuthenticationStateProvider` somewhere in your app, resolving the user's `AuthenticationState` from it, and using the `AccessToken` from the resulting object.

**Comment by T3mmyKay** [comment]
Please if you don't mind can you show me an example I am sort of a newbie

**Comment by YuriyDurov** [comment]
@T3mmyKay I guess you could start [here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-8.0). This is not really related to **Blazor.Auth** so you might be better off searching the web on this, there should be plenty of information on the topic of securing Asp.Net Core WebAPIs.
