### ISSUE TITLE
How to integrate with API Controllers

### ISSUE THREAD

**Issue by YouSeeLA** [BitzArt/Blazor.Auth#23]
First, thanks for the authentication library :)

Would love to see an example of how to authenticate against API Controllers with Blazor.Auth

**Comment by YuriyDurov** [comment]
Hello @YouSeeLA 
Blazor.Auth does not cover WebAPI auth functionality, please use something else to implement auth in your WebAPIs.

[Here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication) is the Microsoft documentation on the topic.

**Comment by YouSeeLA** [comment]
Ok, what you're saying is that I can't use the token created with Blazor.Auth to secure my API? 
So I need to create a separate JWT-based authentication against my API?
Will you develop support for WebAPI with Blazor.Auth? 
It would be very good to have a complete solution, as WASM in most cases always needs to retrieve data from WebAPI.

**Comment by YuriyDurov** [comment]
**Blazor.Auth** does not create access tokens, it requires you to provide the user's tokens via the `IAuthenticationService` that needs to be registered in the server part of the app.

You can also use these tokens to authorize users against your WebAPI, but this functionality is not going to be a part of **Blazor.Auth** (how would that even make sense?)

There is probably a lot of existing implementations that would be compatible with **Blazor.Auth** out there. For example, I am aware of an approach utilizing a custom `AuthorizeAttribute` and a couple of others. But neither of these approaches has anything to do with **Blazor.Auth**, aside from the fact the the access tokens used to authenticate the users are the same.

**Blazor.Auth** is not an all-encompassing auth framework. It is just a library that allows you to integrate Blazor apps with your existing JWT auth schemes. It is highly adaptable to allow it to be used in conjunction with JwtPair-based auth schemes, but it's purpose was never to cover your every authentication/authorization need like securing WebAPIs or something else. It's purpose is solely to allow you to integrate your JWT auth schemes with your Blazor apps.
