### ISSUE TITLE
JWT error using example from the home page

### ISSUE THREAD

**Issue by DrHoneyBear** [BitzArt/Blazor.Auth#25]
Reading this and implementing the examples from that page...
https://bitzart.github.io/Blazor.Auth/01.introduction.html

I am trying to use this excellent system, and have coded up your example server side service for authentication using your example. However, when signing in I get an error message in the browser. I am zero experienced on this, I have no experience in Authorization ... this is all new to me as is Blazor as is NET. I am using NET 8 with Blazor and Radzen in a Web App  from the 'new project' template in Visual Studio. All I want to do really is authenticate against a list of users I have in a database, i was going to add that bit in the service, but I have'nt got that far !

`SecurityTokenMalformedException: IDX12709: CanReadToken() returned false. JWT is not well formed.
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EncodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.`

followed by

`System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ReadJwtToken(string token)
BitzArt.Blazor.Auth.IdentityClaimsService.BuildClaimsPrincipal(string accessToken)
BitzArt.Blazor.Auth.BlazorAuthenticationStateProvider.GetAuthenticationStateAsync()
Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, int componentId, ArrayRange<RenderTreeFrame> oldTree, ArrayRange<RenderTreeFrame> newTree)
Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, out Exception renderFragmentException)
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(int componentId, RenderFragment renderFragment)
Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToPendingTasksWithErrorHandling(Task task, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(int componentId, ParameterView initialParameters)
Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, bool waitForQuiescence)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__10_0>d.MoveNext()
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`

### Server side service (same as your example)

```
using BitzArt.Blazor.Auth;
using Licensing.Auth.Data;

namespace Licensing.Auth.Services
{
    // Example Authentication Service
    public class AuthenticationService
        : ServerSideAuthenticationService<SignInPayload, SignUpPayload>
    {
        protected override Task<AuthenticationResult> GetSignInResultAsync(SignInPayload signInPayload)
        {
            var jwtPair = CreateSampleJwtPair(); // Replace this with your actual authentication logic

            var authResult = AuthenticationResult.Success(jwtPair);

            return Task.FromResult(authResult);
        }

        protected override Task<AuthenticationResult> GetSignUpResultAsync(SignUpPayload signUpPayload)
        {
            var jwtPair = CreateSampleJwtPair(); // Replace this with your actual authentication logic

            var authResult = AuthenticationResult.Success(jwtPair);

            return Task.FromResult(authResult);
        }

        public override Task<AuthenticationResult> RefreshJwtPairAsync(string refreshToken)
        {
            var jwtPair = CreateSampleJwtPair(); // Replace this with your actual authentication logic

            var authResult = AuthenticationResult.Success(jwtPair);

            return Task.FromResult(authResult);
        }

        private JwtPair CreateSampleJwtPair()
        {
            return new JwtPair
            {
                AccessToken = "my-access-token",
                RefreshToken = "my-refresh-token"
            };
        }
    }

}
```

### Payload:

```
namespace Licensing.Auth.Data
{
    // Example Sign-In payload
    public class SignInPayload
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
```

### And the login ... here OnLogin is getting called from a login form, which then calls SignInAsync

```
namespace Licensing.Auth.Pages;

using Licensing.Auth.Data;
using Microsoft.AspNetCore.Components;
using Licensing.Auth.Services;
using BitzArt.Blazor.Auth;
using Radzen;


public partial class AuthLogin
{
    [Inject] NavigationManager NavigationManager { get; set; } = null!;
    [Inject] IUserService UserService { get; set; } = null!;

    public string userName = "admin";
    public string password = "admin";
    public bool rememberMe = true;


    async void OnLogin(LoginArgs args, string name)
    {
        Console.WriteLine($"{name} -> Username: {args.Username}, password: {args.Password}, remember me: {args.RememberMe}");
        await SignInAsync();
    }

    void OnRegister(string name)
    {
        Console.WriteLine($"{name} -> Register");
    }

    void OnResetPassword(string value, string name)
    {
        Console.WriteLine($"{name} -> ResetPassword for user: {value}");
    }

    private async Task SignInAsync()
    {
        var payload = new SignInPayload();
        var authenticationResult = await UserService.SignInAsync(payload);
        NavigationManager.NavigateTo("/", true);
    }

    private async Task SignOutAsync()
    {
        await UserService.SignOutAsync();
        NavigationManager.NavigateTo("/", true);
    }
}
```

**Comment by YuriyDurov** [comment]
Hello @DrHoneyBear 

That sample code is there purely for demonstration purposes, and not exactly supposed to be a real working solution. It is expected that you would replace the JWT pair in that sample with your actual JWTs.

**Blazor.Auth** is trying to read the access token as if it was an actual JWT but it is just a sample string there. So that's why you are getting this exception about it not being able to parse that access token.

If you are looking for an actual working sample application, you can find one [here](https://github.com/BitzArt/Blazor.Auth/tree/main/sample%2FBitzArt.Blazor.Auth.SampleApp).

Let me know if this helps 🙏

**Comment by DrHoneyBear** [comment]
Ahhh. I see. 

Ok from ..

https://github.com/BitzArt/Blazor.Auth/blob/main/sample/BitzArt.Blazor.Auth.SampleApp/BitzArt.Blazor.Auth.SampleApp

... I took your server side service, your jwt service, updated Program.cs to register them, and re-built. VOILA. Runs and "authenticates". But that is without any db access. Clearly I need to add some db work to read username and password from the payload ... but what is this 'authentication' ... does it have authorisation and roles? if not how might I add this please.

THANK YOU for getting me working.

**Comment by YuriyDurov** [comment]
@DrHoneyBear 

Take a look at the sample JWT service in the server side of the app. It builds example JWTs but you now need to build an actual JWT for the user and populate it with the user's claims.

You can put any information you deem necessary into the claims, and you will then be able to see that same information when the user uses those JWTs to access your app. Think UserId, Email, Name, Roles, etc.

The information you encode into a JWT will be accessible by injecting the `AuthenticationStateProvider` anywhere in the Blazor app and then calling it's `GetAuthenticationStateAsync` method. The resulting object will contain the user's claims.

As for the **Authorization** side of things, **Blazor.Auth** integrates with what is provided by the **Blazor**'s framework for this. So you can refer to the **Blazor**'s [documentation on the topic](https://learn.microsoft.com/en-us/aspnet/core/blazor/security).

**Comment by DrHoneyBear** [comment]
Sorry, please can you help a little more. Example...pointer...files you refer to. I am only 3 months into learning Visual Studio , NET Core, SDK, Blazor, Radzen and web app development. We all had to learn somewhere and ask questions. Just a bit more help please. It's 17:10 GMT so going home now and will pick this up ( hopefully :) ) tomorrow 08:00. Thank you for sticking with me.

**Comment by YuriyDurov** [comment]
Sure no worries 👌

**Comment by DrHoneyBear** [comment]
p.s. Where is AuthenticationStateProvider ?? this isnt compling...

  [Inject] AuthenticationStateProvider myASP{  get; set; }

**Comment by DrHoneyBear** [comment]
EDIT. Did you mean BlazorAuthenticationStateProvider.cs , the one in your source tree ?

**Comment by YuriyDurov** [comment]
We can continue with this conversation on our [Discord server](https://discord.gg/G2BHM8jP)

**Comment by DrHoneyBear** [comment]
Hi. it's fine. I figured it out from reading that link to Microsoft. Didn't
know it was integrated so I can use Blazor / ASP attributes and
directives.. all good now. give thanks to you the main man

**Comment by DrHoneyBear** [comment]
Hi.
I do but want to use Discord because it wants me to verify by my phone
number. I do but share my phone number at all.
May I ask you please one more...
How can I use your library to use ROLES not Claims. So that I can use for
example...

<AuthorizeView Roles="Admin">
    <p>User: @context.User</p>
    <p>You have the 'Admin' role claim.</p>
    <AuthorizeView Roles="Superuser" Context="innerContext">
        <p>User: @innerContext.User</p>
        <p>You have both 'Admin' and 'Superuser' role claims.</p>
    </AuthorizeView>
</AuthorizeView>


I only see how Claim is set in your sharing project.

regards
Dr.

**Comment by YuriyDurov** [comment]
@DrHoneyBear 

Hey there!

Yep, I just checked and this seems to work:

```csharp
var accessToken = _tokenHandler.WriteToken(new JwtSecurityToken(
    claims:
    [
        new Claim(ClaimTypes.Role, "Admin")
    ],
    notBefore: now,
    expires: accessTokenExpiresAt,
    signingCredentials: _signingCredentials
));
```

And then

```csharp
<AuthorizeView Roles="Admin">
    <p>You are an admin.</p>
</AuthorizeView>
```
