### ISSUE TITLE
Automatic logout or redirect to login, when token is expired, without userinteraction.

### ISSUE THREAD

**Issue by JensLimberger** [BitzArt/Blazor.Auth#26]
As long as the accesstoken is valid nothing happens, when the user reloads a page or browses to another page.
As long as the refreshtoken is valid, the JWTPair is refreshed, when the user reloads a page or browses to another page.
As soon as the refreshtoken is expired, the user is no longer authenticated, when he reloads the page or browses to another.
But, when you remain on a page without reloading or browsing, you can szill see the authorizeview parts, even, when the refreshtoken is expired.
Can you implement that the user is redirected to loginpage or loggedout as soon as the token is expired?

Thank you very much.

**Comment by YuriyDurov** [comment]
Hello @JensLimberger!

I understand your concern.

Unfortunately this behavior is defined in Blazor and we cannot change it with this library. Blazor only calls our `AuthenticationStateProvider` once per scope - and does not refresh the `AuthenticationState` until the next navigation.

You can inject the `AuthenticationDtateProvider` anywhere in your app and call it's `GetAuthenticationStateAsync` method. This will process the user's authentication state every time you call it and this way it will be up to date.

But we cannot force feed the update to Blazor. The framework does not request an update, and we are not aware of any ways to make it request it.

You could probably try and add a `Timer` to your pages to check the user's authentication state periodically. Once the user is no longer authenticated, you could redirect them to wherever you need. Again, this can be done by injecting `AuthenticationStateProvider` somewhere in your app and then calling it's `GetAuthenticationStateAsync` method. The resulting object will indicate an unauthenticated user as soon as the user's tokens expire.

**Comment by YuriyDurov** [comment]
I will be closing this for now, let me know if any additional assistance is required!
