### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sam-wheat** [BitzArt/Blazor.Auth#8]
Put a breakpoint in the catch block in the Home page of the attached app.
Run the app and click on various pages in the nav menu .  After about 5-10 clicks the program crashes with this error:

    'System.Exception: Server responded with status code 'InternalServerError'.
       at BitzArt.Blazor.Auth.ClientSideAuthenticationService.SignInAsync(Object signInPayload)
       at BitzArt.Blazor.Auth.UserService.SignInAsync(Object signInPayload)
       at Bitzart.Blazor.Auth.Example.Client.Pages.Home.OnInitializedAsync() in C:\Projects\Bitzart.Blazor.Auth.Example\Bitzart.Blazor.Auth.Example\Bitzart.Blazor.Auth.Example.Client\Pages\Home.razor:line 20'

![image](https://github.com/BitzArt/Blazor.Auth/assets/16885210/b34f57c9-b40e-4eae-82c3-472440d8a999)

Only thing I can think of is that perhaps I should be checking if the user is signed in before signing in again?  However in that case it should crash on the first attempt, correct?
[Bitzart.Blazor.Auth.Example.zip](https://github.com/BitzArt/Blazor.Auth/files/15297971/Bitzart.Blazor.Auth.Example.zip)

**Comment by YuriyDurov** [comment]
@sam-wheat

Thanks, we have found out that there was a bug with serializing authentication payloads in Blazor.Auth

We have published a new package version `0.2.3` which contains a fix. Let me know if this resolves your issue!

**Comment by sam-wheat** [comment]
Thank you!  I will try it shortly.  Am facing many unrelated issues with Blazor however.

**Comment by sam-wheat** [comment]
Seems to be working in the sample app.
