### ISSUE TITLE
Can I use Blazor.Auth with other dotnet authentication options?

### ISSUE THREAD

**Issue by sam-wheat** [BitzArt/Blazor.Auth#9]
I have implemented Blazor.Auth in my app - it is very easy to use, thank you!  I can access the cookie and set and get claims.

At this point I need to persist the cookie when browser is closed, and I need to delete the cookie when the user logs out.
Can you direct me to resources that will show me how to do this in a way that does not conflict with Blazor.Auth?

Resources I have found are shown below but in all cases I will need to add additional configuration in startup - and I don't want that configuration to conflict with Blazor.Auth.

https://andrewhalil.com/2020/08/27/persisting-jwt-tokens-in-your-net-core-applications/

https://auth0.com/blog/whats-new-dotnet8-authentication-authorization/

https://www.dominikzoechbauer.com/blog/2021-02-20/combining-and-cookie-jwt-bearer-authentication/

**Comment by YuriyDurov** [comment]
@sam-wheat 

Sure!

Our documentation is lacking in some important aspects.

I have added two additional sections to the documentation. Here is what has been added. Pls let me know if this answers your questions.

#### Token duration

You can specify the duration of your access token and refresh token whenever you are providing your `JwtPair` to Blazor.Auth. The duration of the access token should be short, while the refresh token should normally be long-lived. 

```csharp
return new JwtPair
    {
        AccessToken = "my-access-token"
        RefreshToken = "my-refresh-token"
        AccessTokenExpiresAt = DateTimeOffset.UtcNow.AddMinutes(15),
        RefreshTokenExpiresAt = DateTimeOffset.UtcNow.AddDays(7)
    }
```

> ⚠️
> Not providing an expiration date for the access token will result in the tokens being session-scoped. This means that the tokens will expire when the browser tab closes.

#### Sign out

You can sign the user out by calling the `SignOutAsync` method of the `IUserService`. This will clear the user's JwtPair.

```csharp
await UserService.SignOutAsync();
NavigationManager.NavigateTo("/", true);
```

**Comment by sam-wheat** [comment]
Works perfect, thank you.
